[package]
name = "mock-rollups-machine-manager"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mock-rollups-machine-manager"
path = "src/main.rs"

[dependencies]
tonic = "0.5"
prost = "0.8"
async-trait = "0.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
mockall = "0.10"

[build-dependencies]
tonic-build = "0.5"
