[package]
name = "mock-rollups-machine-manager"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mock-rollups-machine-manager"
path = "src/main.rs"

[dependencies]
async-trait = "0.1"
prost = "0.8"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.5"

[dev-dependencies]
mockall = "0.10"

[build-dependencies]
tonic-build = "0.5"
